name: assignment4

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_success: ${{ steps.set-build-success.outputs.build_success }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize log file with start time and submitter names
        id: init-log
        run: |
          echo "$(date -Iminutes)" > log.txt
          echo "Ron Bitton, Rotem Haim" >> log.txt

      - name: Build Docker Images
        run: |
          set +e
          docker build -t stocks-1a:latest -f ./StocksService/Dockerfile .
          EXIT1=$?
          docker build -t capital-gains:latest -f ./CapitalGainsService/Dockerfile .
          EXIT2=$?
          if [ $EXIT1 -eq 0 ] && [ $EXIT2 -eq 0 ]; then
              echo "images successfully built" >> log.txt
          else
              echo "images not able to be built" >> log.txt
              exit 1
          fi
          set -e

      - name: Save Docker images as tar files
        run: |
          docker save stocks-1a:latest -o stocks-1a.tar
          docker save capital-gains:latest -o capital-gains.tar

      - name: Upload Docker image artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: |
            stocks-1a.tar
            capital-gains.tar

      - name: Upload log artifact (build stage)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: log
          path: log.txt

      - name: Set build success output
        id: set-build-success
        run: echo "::set-output name=build_success::true"

  test:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      test_success: ${{ steps.set-test-success.outputs.test_success }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Docker image artifacts from build job
        uses: actions/download-artifact@v4
        with:
          name: docker-images
          path: ./images

      - name: Load stocks-1a image
        run: docker load -i ./images/stocks-1a.tar

      - name: Load capital gains image
        run: docker load -i ./images/capital-gains.tar

      - name: Download log artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: log
          path: .

      - name: Start Docker Compose services
        id: docker-compose-up
        run: |
          # Start the services as defined in your docker-compose.yml
          docker compose up -d
          # Wait a bit for services to start
          sleep 15
          # Verify that the stocks service container is running
          if docker ps | grep -q "stocks-1a"; then
            echo "Container up and running" >> log.txt
          else
            echo "Container failed to run" >> log.txt
            exit 1
          fi

      - name: Run pytest tests for stocks service
        id: pytest-run
        continue-on-error: true
        run: |
          pip install pytest requests
          pytest -s -v tests/assn4_tests.py | tee assn4_test_results.txt
          exit ${PIPESTATUS[0]}

      - name: Append pytest result status to log
        run: |
          if grep -q "failed" assn4_test_results.txt; then
            echo "tests failed" >> log.txt
          else
            echo "tests succeeded" >> log.txt
          fi

      - name: Upload pytest results artifact
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: assn4_test_results.txt

      - name: Upload updated log artifact (after tests)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: log
          path: log.txt
          overwrite: true

      - name: Tear down Docker Compose (test job)
        if: always()
        run: docker compose down

      - name: Set test success output
        id: set-test-success
        run: |
          if grep -q "tests succeeded" log.txt; then
            echo "::set-output name=test_success::true"
          else
            echo "::set-output name=test_success::false"
          fi

  query:
    name: query
    runs-on: ubuntu-latest
    needs: test
    if: needs.test.outputs.test_success == 'true'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create response.txt File
        run: touch response.txt

      - name: Start Docker Compose services
        run: docker compose up -d

      - name: Wait for services
        run: sleep 15

      - name: Issue 6 POST requests to add stocks entries
        run: |
          curl -X POST http://localhost:5001/stocks -H "Content-Type: application/json" -d '{"name": "NVIDIA Corporation", "symbol": "NVDA", "purchase price": 134.66, "purchase date": "18-06-2024", "shares": 7}'
          curl -X POST http://localhost:5001/stocks -H "Content-Type: application/json" -d '{"name": "Apple Inc.", "symbol": "AAPL", "purchase price": 183.63, "purchase date": "22-02-2024", "shares": 19}'
          curl -X POST http://localhost:5001/stocks -H "Content-Type: application/json" -d '{"name": "Alphabet Inc.", "symbol": "GOOG", "purchase price": 140.12, "purchase date": "24-10-2024", "shares": 14}'
          curl -X POST http://localhost:5001/stocks -H "Content-Type: application/json" -d '{"name": "Tesla, Inc.", "symbol": "TSLA", "purchase price": 194.58, "purchase date": "28-11-2022", "shares": 32}'
          curl -X POST http://localhost:5001/stocks -H "Content-Type: application/json" -d '{"name": "Microsoft Corporation", "symbol": "MSFT", "purchase price": 420.55, "purchase date": "09-02-2024", "shares": 35}'
          curl -X POST http://localhost:5001/stocks -H "Content-Type: application/json" -d '{"name": "Intel Corporation", "symbol": "INTC", "purchase price": 19.15, "purchase date": "13-01-2025", "shares": 10}'
      
      - name: Execute Queries from query.txt
        run: |
          touch response.txt
          while IFS= read -r line || [ -n "$line" ]; do
            SERVICE=$(echo "$line" | cut -d':' -f1)
            # Remove carriage returns and trim whitespace
            QUERY=$(echo "$line" | cut -d':' -f2- | tr -d '\r' | xargs)
            echo "query: ${SERVICE}:${QUERY}" >> response.txt
            echo "response:" >> response.txt
            if [[ "$SERVICE" == "stocks" ]]; then
              curl -s "http://localhost:5001/stocks?$QUERY" >> response.txt
            elif [[ "$SERVICE" == "capital-gains" ]]; then
              curl -s "http://localhost:5003/capital-gains?$QUERY" >> response.txt
            fi
          done < query.txt

      - name: Upload Respone
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: query_responses
          path: response.txt